  - name: Adicionando repositório Zabbix
    dnf:
      name: "{{ item }}"
      state: present
    with_items:
      - http://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/
      - zabbix-server-pgsql-6.0.12
    register: result
    notify: update

  - name: Configurando arquivo de configuração do Zabbix Server
    template:
      src: zabbix_server.conf.j2
      dest: /etc/zabbix/zabbix_server.conf
  - name: Iniciando o serviço Zabbix Server
    service:
      name: zabbix-server
      state: started